### ISSUE TITLE
This doesn't look right

### ISSUE THREAD

**Issue by RebeccaStevens** [vitaly-t/iter-ops#100]
https://github.com/vitaly-t/iter-ops/blob/f752a64c3fc3990850b5caa5374e3796b805c3e3/src/helpers.ts#L144-L162

So the code is saying:
If the value to get an iterable of is a promise. Wait for the process to fulfill. Return the promise's result wrapped in an iterator result; marked as not the last element of the iterator. The next value of the iterator is `undefined` and is the last element of the iterator.

This probably wasn't what was intended.

If I remove that code; the only test that fails is the one specifically testing this. So none of the actual operations are using this behavior and thus I believe this is probably left over code that isn't actually used anymore.

**Comment by vitaly-t** [comment]
Nope, everything there is exactly by design, including the test.

You can test it locally, give it a promise, and see how it works ;)

**Comment by RebeccaStevens** [comment]
In that case, why isn't the iterator just like this:

```ts
if (isPromiseLike(i)) { 
     return { 
         [$A](): AsyncIterator<T> { 
             return { 
                 next(): Promise<IteratorResult<T>> { 
                     return i.then((value: T) => ({value, done: true})); 
                 }, 
             }; 
         }, 
     }; 
 } 
```

**Comment by vitaly-t** [comment]
> In that case, why isn't the iterator just like this:

Because that way the iterator has no termination logic at all, it's iternal :smile:

**Comment by RebeccaStevens** [comment]
Ahh, right. Just me misremembering how iterators work

**Comment by vitaly-t** [comment]
That's why you should see a lot of `finish` - bound logic in the library, to explicitly separate a sequence of values from its termination value.

**Comment by RebeccaStevens** [comment]
I believe there is a small bug though.

With the following line, if `i` is only `PromiseLike` then the return value is only guaranteed to be `PromiseLike`, not a `Promise`. But an `AsyncIterator`'s next function must return an actual `Promise` (at least according to the TypeScript typings).

```ts
return i.then((value: T) => ({value, done: false}));
```

**Comment by vitaly-t** [comment]
I wouldn't consider it a bug, it's more like the thing we are not supposed to care about. We do only Promise-Like check for performance reasons. But documentation states everywhere that we work with promises only.

That promise-like check should be sufficient though.

**Comment by RebeccaStevens** [comment]
hmmm, in that case; it might be best to change `isPromiseLike` back to `isPromise` and just add a note to say that it's not using `instanceof` for performance reasons.

**Comment by vitaly-t** [comment]
> add a note to say that it's not using `instanceof` for performance reasons

Not just performance reasons, but also because `Promise` is often overridden by custom implementations, like `bluebird`.

I think at this point best is to leave it as is, it's not that important. After all, it is not part of the public API, it's just an internal implementation aspect.

**Comment by RebeccaStevens** [comment]
> Promise is often overridden by custom implementations, like bluebird

I was going with the line of thought of custom implementations of promises not being of type `Promise`; but instead only being of type `PromiseLike`. Thus if `PromiseLike` isn't being supported then neither would custom implementations be.
