### ISSUE TITLE
optimizeIterable doesn't work with SharedArrayBuffer

### ISSUE THREAD

**Issue by RebeccaStevens** [vitaly-t/iter-ops#103]
`ArrayBuffer` work but not `SharedArrayBuffer`.

**Comment by RebeccaStevens** [comment]
[Fixed on here](https://github.com/RebeccaStevens/iter-ops/tree/shared-array-buffer) but this relies on #96 so I'll open a PR for it once that is merged.

**Comment by vitaly-t** [comment]
I'm parking it here, for now, will return after New Year. Happy New Year! ;)

**Comment by RebeccaStevens** [comment]
You too

**Comment by vitaly-t** [comment]
@RebeccaStevens 
This needs to be re-visited 😉

**Comment by vitaly-t** [comment]
@RebeccaStevens Can we add the fix, please, if it is not there yet?

**Comment by RebeccaStevens** [comment]
PR opened

**Comment by vitaly-t** [comment]
Thank you!!!! 👍
