### ISSUE TITLE
Add operator flat

### ISSUE THREAD

**Issue by RebeccaStevens** [vitaly-t/iter-ops#107]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

There is already the `spread` operator which is almost the same as `flat`; except that `spread `throws when it encounters a non-iterable while `flat` should keep the value as is.

For example:

```ts
const data = [1, [2, 3], 4, [[5, 6]]];

pipe(data, spread());      // => throws "Value at index 0 is not iterable: 1"
pipe(data, flat());        // => [1, 2, 3, 4, [5, 6]];
```

Alternatively the behavior of `spread` could be altered to work like `flat`.

**Comment by vitaly-t** [comment]
> Alternatively the behavior of `spread` could be altered to work like `flat`.

The way `spread` works is consistent with how JavaScript's native `spread` operator works, i.e. it throws a similar error if you pass it a non-iterable.

For that reason, the only good option to consider is to add a separate `flat` operator.

**Comment by vitaly-t** [comment]
I have started working on this, within [branch flat](https://github.com/vitaly-t/iter-ops/tree/flat).

**Comment by vitaly-t** [comment]
I was just thinking, that our `flat` implementation would be different from `Array.prototype.flat()`, because the latter does not split strings into letters, for example, while we probably should?

Operator `spread` will spread everything iterable. Now I'm trying to decide whether our `flat` should do the same or to be consistent with `Array.prototype.flat()`?

@RebeccaStevens What do you think?

**Comment by vitaly-t** [comment]
Since I haven't quite decided, plus the recursive resolution (per optional `depth`) makes it way more complex an operator.

All my latest is inside `flat` branch, though it is not much yet. But if you want to have a go at it - you're most welcome!

**Comment by RebeccaStevens** [comment]
I'll take a look at it and see what I can do.

If it proves too difficult, maybe we just drop this operator and have `flat` just be an alias for `spread`.

**Comment by vitaly-t** [comment]
After having looked at the Array flat, it looks way different, as it supports nesting, plus doesn’t show errors. Nesting is the tricky part, it would be the first operator that requires recursion.

**Comment by vitaly-t** [comment]
On my second take, I realized it is actually much simpler than I initially thought. In fact, it is even simpler than `spread` logic.

**Comment by vitaly-t** [comment]
`flatSync` is finished and checked in, in branch `flat` ;)

`flatAsync` is yet to be done...

**Comment by vitaly-t** [comment]
The async version is way more tricky, as it needs to handle (differently) both sync and async nested sub-iterables.

**Comment by vitaly-t** [comment]
The async flat has been implemented.

What remains: 

* Some code refactoring (feel free helping with that) @RebeccaStevens :wink:
* Documentation updates
* Better test coverage

**Comment by vitaly-t** [comment]
I have published [2.0.0-beta.2](https://github.com/vitaly-t/iter-ops/releases/tag/2.0.0-beta.2) that includes [flat](https://vitaly-t.github.io/iter-ops/functions/flat.html) operator :wink:

**Comment by vitaly-t** [comment]
Operator [flat](https://vitaly-t.github.io/iter-ops/functions/flat.html) is now fully finished.

@RebeccaStevens If you find any problem with it, we can open a new issue for it ;)

**Comment by vitaly-t** [comment]
The only thing I do not like about this new operator is its name - `flat`.

All other operators in the library are either nouns that denote the result, or verbs - denoting the action. And `flat` doesn't do any of that, it's supposed to be `flatten`.

The only reason we called it `flat` is to have the visual match with the stupid [Array.prototype.flat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) naming.

**Comment by vitaly-t** [comment]
Something I'm not sure about output types:

![image](https://user-images.githubusercontent.com/5108906/193367941-6deab414-11d4-4e53-aa3c-dbbc47fc5edd.png)

The type happens to depend on the `depth` parameter here, so I'm not sure what correct output template should be...

@RebeccaStevens Any idea?

**Comment by RebeccaStevens** [comment]
Ah, that should be achieveable with overloads. Not sure if it can be generalized, will need to look into it.
