### ISSUE TITLE
Add operator flatMap

### ISSUE THREAD

**Issue by RebeccaStevens** [vitaly-t/iter-ops#108]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

Related to #107

There is already the `map` and `spread` operators which together is almost replicate the behavior of `flatMap` but I believe it would be best to add a specific `flatMap` operator; for the same reasoning `flatMap` was added to Array when it already had `map` and `flat`.

For example:

```ts
const data = [1, 2, 3, 4];

pipe(data, map(value => [value, value * 10]]), spread());      // => [1, 10, 2, 20, 3, 30, 4, 40]
pipe(data, flatMap(value => [value, value * 10]));             // => [1, 10, 2, 20, 3, 30, 4, 40]
```

**Comment by vitaly-t** [comment]
@RebeccaStevens A little unrelated...

I really appreciate all the contribution you've done to this project, great job! I didn't intend to make it look abandoned, but the time was bad.

I've just done the initial come back to this project, updated all the dependencies, [documentation], etc. (small things). Currently, reviewing all the old PR-s and issues, to see how to pick it up again.

Just to let you know, in case you are still interested ;)

**Comment by RebeccaStevens** [comment]
I was actually just thinking about this project again. I'm keen to help.

**Comment by vitaly-t** [comment]
> I was actually just thinking about this project again. I'm keen to help.

Great! Thank you! In that case, could you, please, review your old PR-s, and let me know maybe the top 1, 2, 3 most important ones to be merged first, and see they do not have conflicts with the latest code. That would be a good start ;) Whenever you have time! Cheers!

**Comment by vitaly-t** [comment]
The suggested `flatMap` would be much faster and simpler than the two operators, i.e. it would do everything in one loop, and not bother with throwing an error when a non-iterable is encountered.

It can make a good addition, once all other issues have been closed.

**Comment by vitaly-t** [comment]
Now that we have the new [flat](https://vitaly-t.github.io/iter-ops/functions/flat.html) operator, the combination of `map` + `flat` exactly replicates `flatMap` logic, which reduces the need for adding a dedicated operator for it.

**Comment by vitaly-t** [comment]
After another look into `flatMap` operator, here are two good reasons not to add one:

* Confusing name. One may think that `flatMap` is an operator that first flattens the data and then re-maps it, whereas in fact it is the other way round, the data is re-mapped before it is flattened. When used separately, you can do both, and without ambiguity, which means you can also flatten data and then re-map it.
* Limited depth. The standard `flatMap` works only with `depth=1`, which you cannot change, whereas when using operator `flat` separately, you can specify `depth`.

The only thing going for adding `flatMap` is shorter, though confusing syntax, and slightly better performance. But that's not enough to justify adding it.

**Comment by RebeccaStevens** [comment]
`flatMap` is a function I use on arrays quite a lot. The main reason I really want it is because it make the code a lot more readable.

```ts
someArray.flatMap((value) => {
  // Some
  // Some
  // Some
  // Some
});

**Comment by RebeccaStevens** [comment]
Also, I'm all for renaming the `flat` operator to `flatten` as that is the more commonly used term when it comes to functional programming.

**Comment by vitaly-t** [comment]
Fair enough,... I'm not sure if I will have the time to get it properly done...

But I created branch `flat-map`, in which I have implemented the sync version of it (draft, without tests).

Feel free to pick it up, if you want ;)

**Comment by vitaly-t** [comment]
**UPDATE:** I have added the async also, seems working, but needs proper tests.

**Comment by vitaly-t** [comment]
I did some refactoring + added empty tests. I cannot run tests presently anyway 😢

**Comment by vitaly-t** [comment]
Now that I at least was able to run `npm run test:js`, I have added all the required tests for `flatMap`.

**Comment by vitaly-t** [comment]
The operator has been merged into `master`.

**Comment by vitaly-t** [comment]
This task is now complete. Closing.
