### ISSUE TITLE
Typed with `undefined`

### ISSUE THREAD

**Issue by scallaway** [vitaly-t/iter-ops#118]
I've stumbled across this library as we're finding that we're doing a lot of conversions from `x.values()` to arrays in order to then run the appropriate functions on them. I figured I'd give this library a go in order to reduce the amount of code that we have to write.

However, it seems that there _always_ appears to be a chance that `pipe` is going to return `undefined` for the `first` field (according to the types) that it exposes to the consumer. This means that I'm forever having to write checks to ensure that the value I'm pulling out is indeed there, and isn't `undefined` like the types indicate it might be.

Is there another way that I'm meant to be pulling out the value? This is especially apparent when calling functions that should return booleans such as `some`. Am I not meant to be using `first`?

I checked the tests defined in here for some guidance, but they all seem to assume that the value is going to be present, no matter what the case.

Any guidance on this would be fantastic!

**Comment by vitaly-t** [comment]
`first` always refers to the first value, and if there isn't any, it returns `undefined`.

If you need to make sure the `undefined` values are distinguished, you can simply remap the pipe into something like `{value}`:

```ts
map(a => ({value: a}))
```

Then you will only get `undefined` for the `first` when there are no values. Otherwise, you will have `{value: undefined}`.

**Comment by scallaway** [comment]
Yeah that makes sense, I guess with `undefined` values I'm going to have to consistently check whether the value that I get back from `pipe` is indeed `undefined` or not. I've gone back through what I'd written before and adjusted it accordingly.

However, there is another problem with the way in which `IterableExt` works in more simple cases, which I think is due to the way it's typed (although I'm not 100% on this).

Take this very simple use-case, for example;

```ts
const testMap = new Map<string, number>([
  ["1", 1],
  ["2", 2],
  ["3", 3],
  ["4", 4],
]);
const arr: Array<number> = [];

const mapCollectValues = (inputMap: Map<string, V>) => { // the return type of this is actually IterableExt<Array<V>> 
  return pipe(inputMap.values(), toArray());
}

arr.concat([...testMap.values()]); // typechecks fine
arr.concat(mapCollectValues(testMap)); // doesn't typecheck
```

In both `concat()` cases, the value that I'm providing to the `concat` call _should_ be the same. However, because of the fact that `pipe` returns an `IterableExt`, the TypeScript compiler complains about the second `concat` call.

Is the expectation that I should just be casting here to the internal type of `IterableExt`, or is there another way in which I should be handling cases like this? Of course this is a very simple use-case, but having the resulting collection be an Array is a fairly common operation that we do in our codebase.

Cheers for the help so far!

**Comment by vitaly-t** [comment]
Just spread the values:

```ts
arr.concat(...mapCollectValues(testMap)); // doesn't typecheck
```
