### ISSUE TITLE
Yarn 3

### ISSUE THREAD

**Issue by RebeccaStevens** [vitaly-t/iter-ops#120]
Do we want to update to yarn 3?

**Comment by vitaly-t** [comment]
You are the one who added CI config, so I'm leaving it up to you 😉

**Comment by RebeccaStevens** [comment]
Once consequence of update is that devs (you and me) will need to have yarn 3 install locally. I've got it set up, but I don't want to force you if you don't want it.

**Comment by vitaly-t** [comment]
I don't mind ;)

**Comment by RebeccaStevens** [comment]
alright, I make a PR

**Comment by vitaly-t** [comment]
[Added](https://github.com/vitaly-t/iter-ops/pull/121).

**Comment by RebeccaStevens** [comment]
@vitaly-t Could you confirm that you are using yarn 3?
Yarn 1 lock files seems to be getting checked in.

**Comment by RebeccaStevens** [comment]
> ```
> "packageManager": "yarn@3.2.4",
> ```

This is used by `corepack` which is an opt-in feature of node.

To enable `corepack`, if you are using node 16.10 or newer, run `corepack enable`. This will also enable yarn 3 for you.

https://yarnpkg.com/getting-started/install#nodejs-1610

**Comment by vitaly-t** [comment]
Cool, that worked like a charm ;)
