### ISSUE TITLE
Unknown type issue from Beta 4

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/iter-ops#135]
@RebeccaStevens 

After PR #132, it seems, we start getting `unknown` type resolved...

![image](https://user-images.githubusercontent.com/5108906/193754777-d7501b68-20bd-4704-9c81-baa9db69921f.png)

See 2.0.0.0-beta 4 version published.

**UPDATE**

Actually, after some time, my IDE started showing `spread` with correct type, but not `flat`:

![image](https://user-images.githubusercontent.com/5108906/193755685-8b527bda-f149-4dd9-b4aa-9db758771ea5.png)

**Comment by RebeccaStevens** [comment]
Yeah, I suspected there would be problems like this. I'll be working on that next.
I'm working on finishing up the 5.0 release of `eslint-plugin-functional`.

**Comment by vitaly-t** [comment]
After playing with it a bit more, I'm seeing my IDE (WebStorm) getting confused about types a lot. It was showing correctly for one operator, then suddenly stopped :) I don't know what to make of it :)

**Comment by vitaly-t** [comment]
@RebeccaStevens Just re-tested it against v2.0.0-beta.6

Looks like types for `flat` and `flatMap` are resolved correctly now, but not for `spread`, which produces `unknown` type.

![image](https://user-images.githubusercontent.com/5108906/195511992-ae76ff2c-d161-41be-9f9f-93a492c75c8b.png)

**Comment by RebeccaStevens** [comment]
Isn't this expected as `1`, `2` and `3` are not iterable?

This should work though:

```ts
const data = [[1, 2, 3]];
const i = pipe(data, spread());
```

**Comment by vitaly-t** [comment]
> Isn't that expected as 1, 2 and 3 are not iterable?

Yes, you are right. What actually confused me is that in v1.6.4 it would complain about incorrect input:

![image](https://user-images.githubusercontent.com/5108906/195554676-c58f15ce-6e39-4ffb-8f43-51e2d5e25e26.png)

But with v2.0.0-beta.6 it does not complain.

**Comment by RebeccaStevens** [comment]
When I tried that code, it also complained just like it did in v1.6.4

![image](https://user-images.githubusercontent.com/7224206/195559225-b01523e6-882f-4381-9170-0b120438a598.png)

**Comment by vitaly-t** [comment]
That's odd. I can see that error inside the library tests also, but not inside clients. Tried to clean up the cache - didn't help. Latest TypeScript, latest WebStorm, errors for v1.6.4, not for v2.0.0-beta.6

Any idea? :)

**Comment by vitaly-t** [comment]
@RebeccaStevens If you are certain that there is no issue there, then feel free to close this issue ;)

**Comment by RebeccaStevens** [comment]
![image](https://user-images.githubusercontent.com/7224206/196028544-8bb64bb7-8ea0-4fe7-8e2c-a8cf5cda2012.png)

I'm getting the error, so I think everything is working as exoected.
