### ISSUE TITLE
Removing async/await code

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/iter-ops#156]
When I started on this library, a lot of time asynchronous implementation was simply copied from synchronous, with added `async/await`  usage, in order to save time (plus some operators have fairly complex logic).

However, performance tests showed that native `.then.catch` solution performs way better than `async/await`, so I've been converting async operators to use `.then.catch` syntax only (see #76).

There are still some operators remain that rely on `async/await` syntax. Mostly it is because they have fairly complex logic, which makes conversion quite a challenge.

This issue is to track the async operators that still need to be converted:

- [x]  `concat` - this should take priority, as the most frequently used one 🏁 
- [x]  `defaultEmpty`
- [ ]  `repeat`
- [ ]  `split` - the most complex operator in the library, likely with some issues - #33

P.S. @RebeccaStevens In case nothing else challenges you here :wink:

---

Related: #76

**Comment by RebeccaStevens** [comment]
I'm actually kind of curious whether using callbags would be the best approach. They're super performant and might even be able to dedup a lot of commonalities between the sync and async code.

**Comment by vitaly-t** [comment]
I do not see how callbacks can be used there, since every operator is expected to return a Promise.

**Comment by RebeccaStevens** [comment]
Checkout this talk: https://www.youtube.com/watch?v=Ir9-EBbc9fg&t=1s

**Comment by vitaly-t** [comment]
It would take a bit of research to see if that would even be possible to use, given this library's objectives and current function. And if it were, this issue here is about the implementation aspect, strictly. I prefer to keep it simple.

**Comment by vitaly-t** [comment]
Thank you for looking into this!

The priority here is to get rid of the `async/await` syntax, because it slows things down quite a bit, or at least according to some tests I did in the past.

However, the whole issue isn't really a big deal, certainly not one to justify another major change. That's why I'd prefer to leave it without making any such big change, at least presently.

I appreciate all the work you've been putting into this! And since you like the good challenges, then issue #33 is certainly worth looking into. It is the most complex operator that we have, and I believe some function there is off, along with the tests for it.

**Comment by vitaly-t** [comment]
Finished rewriting operator `concat`, merged into `master`.

**Comment by vitaly-t** [comment]
P.S. Oddly enough, my WebStorm UI fails to detect iterable type correctly when we have more than 2 `concat` parameters, as shown below... even though our own test seems to pass there.

![image](https://user-images.githubusercontent.com/5108906/202834047-c3b648d1-e957-46c6-ba43-1d4ffa41d498.png)

**Comment by vitaly-t** [comment]
[Version 2.3.2](https://github.com/vitaly-t/iter-ops/releases/tag/2.3.2) now has rewritten version of [concat](https://vitaly-t.github.io/iter-ops/functions/concat.html).

**Comment by vitaly-t** [comment]
[Version 2.3.3](https://github.com/vitaly-t/iter-ops/releases/tag/2.3.3) now has rewritten version of [defaultEmpty](https://vitaly-t.github.io/iter-ops/functions/defaultEmpty.html).
