### ISSUE TITLE
2.0.0 checkpoints

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/iter-ops#160]
This is to track what's left before 2.0.0 is released.

* Check that all operators work and cast types as expected.
* Complete #103
* Complete #135

I'm sure there can be more to add or improve, but those won't be breaking changes, so can be added later.

@RebeccaStevens Anything else you can think of as necessary for 2.0.0 release?

**Comment by vitaly-t** [comment]
I added #161 later, as a breaking change, but it is already done and released in Beta 7.

**Comment by vitaly-t** [comment]
#163 Went in with Beta 8

**Comment by vitaly-t** [comment]
@RebeccaStevens Do you think you can make time to review what's left as per the list above?

I really have my mind set for v2.0.0 release to happen today, with what we've got now... 😄

**Comment by RebeccaStevens** [comment]
Sorry, I haven't been feeling well the last few days. I'll take a look at those issue now.

**Comment by vitaly-t** [comment]
I'm very sorry to hear. Get better! 😉

**Comment by vitaly-t** [comment]
@RebeccaStevens Ok, I'm all done here, ready to make v2.0.0 release. Are you ok with that or are you changing something now?

**Comment by vitaly-t** [comment]
[Version 2.0.0 released](https://github.com/vitaly-t/iter-ops/releases/tag/2.0.0).
