### ISSUE TITLE
Extend "last" operator with iteration state

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/iter-ops#170]
## Feature

Add support for `IterationState` to operator [last].

## Why?

Let's say we want to search for border values, like `min` / `max` inside an iterable. Because operator [last] doesn't support iteration state, like `filter` does, we have to use a combination of `filter` + `last`:

```ts
import {pipe, last, filter} from 'iter-ops';

const input = [3, 0, -2, 5, 9, 4];

const iMin = pipe(input, filter((value, idx, state) => {
    if (!idx || value < state.min) {
        state.min = value;
        return true;
    }
}), last());

const iMax = pipe(input, filter((value, idx, state) => {
    if (!idx || value > state.max) {
        state.max = value;
        return true;
    }
}), last());

console.log(...iMin, ...iMax); //=> -2 9
```

Once we have operator `last` support the iteration state, we will be able to simplify that example to just using operator [last]:

```ts
import {pipe, last} from 'iter-ops';

const input = [3, 0, -2, 5, 9, 4];

const iMin = pipe(input, last((value, idx, state) => {
    if (!idx || value < state.min) {
        state.min = value;
        return true;
    }
}));

const iMax = pipe(input, last((value, idx, state) => {
    if (!idx || value > state.max) {
        state.max = value;
        return true;
    }
}));

console.log(...iMin, ...iMax); //=> -2 9
```

Note that operator [last] already supports a callback, and it's just missing the iteration state support.

---

@Jason3S [Per your question](https://github.com/vitaly-t/iter-ops/discussions/115), a good example of why support for iteration state is quite beneficial, and makes processing logic much simpler ;)

@RebeccaStevens What do you reckon? ;)

[last]:https://vitaly-t.github.io/iter-ops/functions/last.html

**Comment by vitaly-t** [comment]
I'm adding the same `state` support to operator `first`, for consistency, which is the only other operator in the library missing it.

**Comment by vitaly-t** [comment]
Implemented and released in [v2.1.0](https://github.com/vitaly-t/iter-ops/releases/tag/2.1.0).

Both `first` and `last` operators now support iteration state.

**Comment by vitaly-t** [comment]
Just for completeness, here's an example of how one calculates an average value from iterable:

```ts
import {pipe, last, map} from 'iter-ops';

const input = [3, 0, -2, 5, 9, 4];

const i = pipe(input, map((value, idx, state) => {
    if (idx) {
        state.sum += value;
        return state.sum / (idx + 1);
    }
    return state.sum = value;
}), last());

console.log(...i); //=> 3.1(6)
```

**Comment by vitaly-t** [comment]
I have amended [Recipes](https://github.com/vitaly-t/iter-ops/wiki/Recipes) with [Border Values](https://github.com/vitaly-t/iter-ops/wiki/Recipes#border-values), to show all these useful examples in practice, and in one place.

**Comment by vitaly-t** [comment]
After #172 fix, I figured out how to get an average value by using just `reduce` operator:

```ts
import {pipe, reduce} from 'iter-ops';

const input = [3, 0, -2, 5, 9, 4];

const i = pipe(input, reduce((prev, curr, idx, state) => {
    state.sum = idx > 1 ? state.sum + curr : prev;
    return state.sum / (idx + 1);
}));

console.log(...i); //=> 3.1666(6)
```

**Comment by vitaly-t** [comment]
This has been fully concluded.

**Comment by vitaly-t** [comment]
@RebeccaStevens Are you still following this project or are you quits? You haven't followed anything, I pinged you for a week.

**Comment by RebeccaStevens** [comment]
Sorry, I'm still here; just been busy lately. I'm currently moving house.

With regards to this issue, I think it is good to add `iteration state` purely because the other operators have support for it.

However, personally I'm with @Jason3S and don't really think it is needed.
For the example you gave of finding min/max values, I would simply use the reduce operator:

```ts
import {pipe, reduce} from 'iter-ops';

const input = [3, 0, -2, 5, 9, 4];

const iMin = pipe(
  input,
  reduce((r, c) => r < c ? r : c)
);

const iMax = pipe(
  input,
  reduce((r, c) => r > c ? r : c)
);

console.log(...iMin, ...iMax); //=> -2 9
```

`iteration state` does exactly what it says on the box, adds state support.
However, I try and make all my code functional rather than iterative unless I have good reason to do otherwise (such as if I need to optimize for performance). The main reason I use this library is because it helps me do precisely this.

**Comment by vitaly-t** [comment]
@RebeccaStevens Good example for min/max! But for calculating the average, for instance, state is required ;)

**Comment by RebeccaStevens** [comment]
I'd probably write it something like this

```ts
const iMean = pipe(
  input,
  reduce(([sum, count], value) => [sum + value, count + 1], [0, 0]),
  reduce((_, [sum, count]) => sum / count, [0, 0]),
);

console.log(...iMean); //=> 3.1666666666666665
```

Or using `aggregate`:

```ts
const iMean = pipe(
  input,
  aggregate(data => data.reduce((a, b) => a + b) / data.length)
);
```

Or to be really fancy:

```ts
const iMean = pipe(
  input,
  lift(
    (sum, count) => sum / count,
    reduce((a, b) => a + b),
    count
  ),
);
```

Where `lift` would be a new operator that would be defined like so:
`lift(f, g, h, ...)(x) <===> f(g(x), h(x), ...(x))`

**Comment by vitaly-t** [comment]
That is a lot of examples, nice! :smile: Still the example I provided is the only one that relies on just one operator, and nothing else :wink:

Copied from [Border Values](https://github.com/vitaly-t/iter-ops/wiki/Recipes#border-values):

```ts
import {pipe, reduce} from 'iter-ops';

const input = [3, 0, -2, 5, 9, 4];

const i = pipe(input, reduce((p, c, idx, state) => {
    state.sum = idx > 0 ? state.sum + c : c;
    return state.sum / (idx + 1);
}, 0));

console.log(...i); //=> 3.1666(6)
```

Also, one with the `aggregate` isn't great, as you end up accumulating all values from potentially an endless generator, which is bad for memory.

**Comment by RebeccaStevens** [comment]
The `lift` one is probably my favorite; we should add a `lift` operator.

**Comment by vitaly-t** [comment]
Is an existing implementation for operator `lift`? I want to understand its general usefulness.

**Comment by RebeccaStevens** [comment]
Here's something that popped up after a quick Google: https://jrsinclair.com/articles/2019/compose-js-functions-multiple-parameters/

**Comment by vitaly-t** [comment]
Interesting, I will look into it.

In the meantime, just added another example into [Border Value](https://github.com/vitaly-t/iter-ops/wiki/Recipes#border-values), for `min` + `max` example...

---

* To produce `min` + `max` values in a single iteration:

```ts
import {pipe, reduce} from 'iter-ops';

const input = [3, 0, -2, 5, 9, 4];

const i = pipe(input, reduce((p, c) => {
    p.min = c < p.min ? c : p.min ?? c;
    p.max = c > p.max ? c : p.max ?? c;
    return p;
}, {min: undefined, max: undefined}));

console.log(...i); //=> { min: -2, max: 9 }
```

Note that in the above implementation, if your input has no values, you will correctly get `{min: undefined, max: undefined}`.

**Comment by vitaly-t** [comment]
@RebeccaStevens That `lift` logic is the old `avelanche` pattern, and essentially what our pipe does, just with simple functions:

```ts
const pipe = (...f) => args => f.reduce((res, a) => a(res), args);
```
