### ISSUE TITLE
Benchmark Readme statement about RXJS subscription is incorrect.

### ISSUE THREAD

**Issue by caleb-vear** [vitaly-t/iter-ops#223]
The benchmark readme states:

> This library performs about 2.5x faster than rxjs synchronous pipeline. However, just as you add a single subscription in rxjs ( which is inevitable with rxjs), then iter-ops performance is about 5x times better. So ultimately, this library can process synchronous iterables about 5x times faster than synchronous rxjs.

However upon examining the benchmark code I think this is a misunderstanding.

<img width="1278" alt="image" src="https://github.com/vitaly-t/iter-ops/assets/261696/1bff2d14-2b4b-4ea5-8c1a-b904f0205a49">

![image](https://github.com/vitaly-t/iter-ops/assets/261696/8c9081e8-93d5-4aac-962d-28b8a44da3b0)

The `firstValueFrom` source can be found here: [https://github.com/ReactiveX/rxjs/blob/7.8.1/src/internal/firstValueFrom.ts#L11-L75](https://github.com/ReactiveX/rxjs/blob/7.8.1/src/internal/firstValueFrom.ts#L11-L75)

So there is actually no need to do a separate subscription.  If you want to simulate where there are multiple subscribers you would want to convert the sequence over to a shared observable using the [share operator](https://rxjs.dev/api/index/function/share).

**Comment by vitaly-t** [comment]
Thanks for pointing this out. That original document was written and tests were done at the time when RxJS v6 was the latest. Some of them can be no longer valid, because numerous performance improvements were done in RxJS since then.

I did some re-testing a few months back, and it performed pretty much on par with the latest RxJS v7, which is very good. I will try to make time later to update the tests.

Still, this library has something unique to offer here - simpler syntax, plus some unique operators, to be considered as an alternative for handling iterables.

**Comment by caleb-vear** [comment]
I agree that iter-ops has something to offer over rxjs.  We are using it on my current project because we have a lot of code that synchronously processes iterable data.  We often want to do multiple steps, e.g. filter, window and map and it is great to not need to loop through multiple times or create unnecessary copies of everything for each step.

**Comment by vitaly-t** [comment]
Yep, and there's plenty more in [iter-ops-extras](https://github.com/vitaly-t/iter-ops-extras) ;)

**Comment by vitaly-t** [comment]
@caleb-vear Would you be interested to PR the necessary change for this?

**Comment by vitaly-t** [comment]
@caleb-vear If you still think that the above is incorrect, then please follow up, and perhaps PR the necessary change. But for the time being, after reviewing it, I see no issue in the current test results. We can re-open the issue later, if you follow up on this, but for the time being, I am closing it.
