### ISSUE TITLE
Update all DEV dependencies

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/iter-ops#236]
Some of the DEV dependencies are quite tricky, and have interdependencies. I am creating this issue, in the hope that @RebeccaStevens will be interested to help update those, as she was the one who had them set up in the first place. I got a bit stuck trying to bring them all up to date.

Hi @RebeccaStevens! Would you, please help us out, to update all DEV dependencies! 🙏 Thank you!!! 🫶

**Comment by RebeccaStevens** [comment]
Can do. I might be able to do it today; no guarantees though.
