### ISSUE TITLE
Tests error on Windows

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/iter-ops#241]
Cannot run tests, after the [DEV Dependencies PR](https://github.com/vitaly-t/iter-ops/pull/240):

![image](https://github.com/user-attachments/assets/194365cc-140f-4d87-b108-f79ff5ffb874)

Running `npm test` produces the above error for me. Could be because I use Windows 11 here? I haven't tried it on Mac yet, will do a little later, if needed. It reproduces using NodeJS 18, 20 and 22.

P.S. I did remove all installed dependencies and reinstalled everything.

**Comment by vitaly-t** [comment]
So I have done some more testing, including on Mac, and I can now confirm that the issue is Windows-specific. I had no issues whatsoever on Mac.

Unfortunately, Windows 11 is my main rig here, so I need to figure it out. Any help is much appreciated!

@RebeccaStevens

**Comment by vitaly-t** [comment]
If I try to use the full path to the `c8` module like this:

```
"test:js": "cross-env TSX_TSCONFIG_PATH=tsconfig.test.json NODE_OPTIONS='--import tsx' node_modules/c8/bin/c8 mocha 'test/**/*.spec.ts'"
```

Then I am getting this:

![image](https://github.com/user-attachments/assets/cbc2f51b-5e8a-468d-973b-e9609df74844)

**Comment by RebeccaStevens** [comment]
Got a potential fix. Weird thing is that one of the tests are failing for me now on windows.

**Comment by vitaly-t** [comment]
That PR does work for me!!! :)

I also see some test issues, but only sometimes, that's because there are some race-condition tests that were tuned to pass under the current test framework. I will just need to fine tune them a little now that the test framework is different ;)

**Comment by RebeccaStevens** [comment]
Figured it out. It's a timing bug.

**Comment by RebeccaStevens** [comment]
Actually, maybe not a bug as such. It looks more intentional so I guess an issue with the test.

**Comment by vitaly-t** [comment]
Values for the test were tuned to pass under the current test framework. But since it is a race-condition test, timings change when the test framework changes, so needs to be updated to pass both on Linux and Windows. That's not something to worry about, I can update any such troubling test ;)

**Comment by RebeccaStevens** [comment]
Alright, I'll leave that all to you. I did make an issue though #243
