### ISSUE TITLE
Typedoc is failing to build documentation

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/iter-ops#245]
After the change, I saw a type-resolution issue within `onEnd` tests, which I fixed according to what it expected, but then `typedoc` stopped working, which apparently relies on running `tsc`, which fails for those tests also.

@RebeccaStevens Any idea why TSC is now failing, and how else that test can make use of type `IIterationSummary`?

If I roll the changes back, it looks like this:

![image](https://github.com/user-attachments/assets/79dd825d-bd35-4cca-b5ea-f9e8ddc994d5)

i.e. it cannot see the type, though it works, and `typedoc` also builds, but in the current code, it looks correct, all valid, but typedoc fails because so does TSC. Any idea what it really should be?

This looks like a conflict between `TSC` compiler and the `type` changes, which only manifests when generating documentation, which relies on running `TSC`.

**Comment by vitaly-t** [comment]
I have reverted the test code into the master, because I need to be able to build documentation. In the meantime, I've noticed this issue isn't limited to `onEnd` operator. The same issue can be seen in tests for operator `timing`.

**Comment by RebeccaStevens** [comment]
Sorry, I'm not sure I follow.
So you're saying you can't build the docs? How are you building them? With `yarn docs`?
That's working for me without issue.

**Comment by vitaly-t** [comment]
As per above, I reverted the code back to your own version, so I can build documentation, by running `npm run doc`.

But as you can see in the screenshots above, the IDE fails to understand tests for operators `onEnd` and `timing`, and so they come up in red. If it is an IDE issue somehow, it would be an odd one.

I can fix the issue by how types `IIterationSummary` and `IValueTiming` are used, but if do, and the IDE likes it, but then `tsc` and `npm run doc` both fail, and I cannot generate documentation.

**Comment by vitaly-t** [comment]
After a bit more playing with it, I think it may be an IDE issue after all, something with failing to pick up the types or linting issue, I'm not sure. But after restarting the IDE, I cannot see the issue again, which is quite odd.

Therefore, I'm just going to close this.

@RebeccaStevens Thank you for looking into this!
