### ISSUE TITLE
[Docs][typedoc] Code section is unreadable 

### ISSUE THREAD

**Issue by FaberVitale** [vitaly-t/iter-ops#64]
caused by `--code-bg` defined in custom.css

#### With `--code-bg`

<img width="849" alt="Screenshot 2021-12-19 at 19 31 05" src="https://user-images.githubusercontent.com/16583125/146686642-754390ba-5df6-422f-8187-30a9ef9731a2.png">

#### Without `--code-bg`

<img width="610" alt="Screenshot 2021-12-19 at 19 33 51" src="https://user-images.githubusercontent.com/16583125/146686728-e39f2c81-e34e-457c-b292-cdd470f5c1a3.png">

**Comment by vitaly-t** [comment]
Ouch! I wasn't aware that one could somehow override the help palette like that. Could you, please tell me how I can achieve the same, for later tests? (I'm using Windows 10) Thank you!

In the meantime, I have updated it - let me know, please, if it looks ok for you now ;)

**Comment by FaberVitale** [comment]
> Ouch! I wasn't aware that one could override the help palette like that.
> 
> I have updated it - let me know, please, if it looks ok for you now ;)

👍 

<img width="864" alt="Screenshot 2021-12-20 at 21 15 42" src="https://user-images.githubusercontent.com/16583125/146827297-f3274862-9f55-4563-a749-5fe73d0aae38.png">

**Comment by vitaly-t** [comment]
Great, closing it then 😄
