### ISSUE TITLE
Unnecessary aliasing

### ISSUE THREAD

**Issue by RebeccaStevens** [vitaly-t/iter-ops#85]
Aliasing `Symbol.iterator` and `Symbol.asyncIterator` to shorter names no longer has any benefit. `Terser` will automatically take care of this.

https://github.com/vitaly-t/iter-ops/blob/40315f0ae8db04ead28b63ec7fee845638055928/src/types.ts#L133-L137

**Comment by vitaly-t** [comment]
Are you sure? Symbols are a special case. I saw those symbols repeated many times inside the minified output files.

**Comment by vitaly-t** [comment]
@RebeccaStevens With all your great help here, I took the liberty of putting your name on the list of contributors [here](https://github.com/vitaly-t/iter-ops/blob/main/package.json#L48).

Please let me know you're ok with that, before I publish the update ;)

**Comment by RebeccaStevens** [comment]
That's all good with me, thanks 😄 

There's a bit of refactoring work I want to make to this project too, if that's ok with you. I'll follow all your styling decisions so if you want to keep things like the aliasing mentioned in this issue, that all good with me.

**Comment by vitaly-t** [comment]
Cool, we're on the same page here :smile:

**Comment by vitaly-t** [comment]
I think this one has been concluded ;)
