### ISSUE TITLE
is Promise or is Promise-like?

### ISSUE THREAD

**Issue by RebeccaStevens** [vitaly-t/iter-ops#95]
Should this be checking if the type is a Promise (as the name suggests) or if it is just Promise-like (as the implementation suggests)?

https://github.com/vitaly-t/iter-ops/blob/523b5880ac54d1bd9759f09da01c23cd76ea7b97/src/utils.ts#L112-L117

The following part of the code would indicated that it's supposed to check that it is an actual Promise (due to the return type of the `next` function).

https://github.com/vitaly-t/iter-ops/blob/523b5880ac54d1bd9759f09da01c23cd76ea7b97/src/helpers.ts#L144-L162

**Comment by vitaly-t** [comment]
Strictly speaking, yes, it is a promise-like check. But since that's an internal function, not exposed by the library, it probably doesn't make any difference.

**Comment by RebeccaStevens** [comment]
I believe that if it is supposed to work as promise-like then the typing in some other places needs to be changed from Promise to PromiseLike. I'll look into this more tomorrow when I tackle trying to remove all the anys.

**Comment by vitaly-t** [comment]
I have fixed linting issues + added comments for `isPromise` ;)

**Comment by vitaly-t** [comment]
Ok, I have renamed it :smile:

**Comment by vitaly-t** [comment]
@RebeccaStevens I have fixed a couple of test issues (timing-specific issues on Linux), and released 1.6.2 update :wink:

Thank you for all the work you've put into this! 👍
